### PR TITLE
Added background color to table

### LINKED ISSUE #2: Table background color
Add CSS to change table background color

### PR DESCRIPTION
**Pull request by Parth-Gupta10**
Fixes #2, Please review @KKhushhalR2405

### CODE REVIEW

**Comment by KKhushhalR2405** [comment]
Commit merged. Nice work @Parth-Gupta10. Happy Hackotber.

**Comment by Parth-Gupta10** [comment]
@KKhushhalR2405 Thanks, Happy Hacktoberfest 🎉

**Comment by Parth-Gupta10** [comment]
@KKhushhalR2405 as per the new rules you need to label my PR as "hacktoberfest-accepted" for it to get counted towards the competition, so can you please add that to my PR.

**Comment by KKhushhalR2405** [comment]
> @KKhushhalR2405 as per the new rules you need to label my PR as "hacktoberfest-accepted" for it to get counted towards the competition, so can you please add that to my PR.

I have added hacktoberfest label to this repo. And all the PRs to such repo are accepted. 😃

**Comment by Parth-Gupta10** [comment]
Thank you very much

**Pull request merged**
